
export const DEFAULT_ACTION = 'app/ExaminePayment/DEFAULT_ACTION';
export const SETTAB_ACTION = 'app/ExaminePayment/SETTAB_ACTION';

export const FETCHINVOICEINFO_ACTION = 'app/ExaminePayment/FETCHINVOICEINFO_ACTION';
export const SETINVOICEINFO_ACTION = 'app/ExaminePayment/SETINVOICEINFO_ACTION';

export const FETCHTASKHISTORY_ACTION = 'app/ExaminePayment/FETCHTASKHISTORY_ACTION';
export const SETTASKHISTORY_ACTION = 'app/ExaminePayment/SETTASKHISTORY_ACTION';

export const FETCHASSOCIATEFILE_ACTION = 'app/ExaminePayment/FETCHASSOCIATEFILE_ACTION';
export const SETASSOCIATEFILE_ACTION = 'app/ExaminePayment/SETASSOCIATEFILE_ACTION';

export const FETCHPREVIEW_ACTION = 'app/ExaminePayment/FETCHPREVIEW_ACTION';
export const SETPREVIEW_ACTION = 'app/ExaminePayment/SETPREVIEW_ACTION';
export const HIDEPREVIEW_ACTION = 'app/ExaminePayment/HIDEPREVIEW_ACTION';